live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11.0

[font.bold]
family = "hack"
style = "Bold"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[scrolling]
history = 0

[window]
decorations = "none"
